/*USE carsOfTheYear;
ALTER TABLE Cars WITH CHECK
ADD CONSTRAINT FK_MFGRID FOREIGN KEY(MFGRID) REFERENCES MFGR(MFGRID)
ON UPDATE CASCADE
ALTER TABLE Cars WITH CHECK
ADD CONSTRAINT FK_StyleID FOREIGN KEY(StyleID) REFERENCES Style(StyleID)
ON UPDATE CASCADE
ALTER TABLE Cars WITH CHECK
ADD CONSTRAINT FK_PerformanceID FOREIGN KEY(PerformanceID) REFERENCES Performance(PerformanceID)
ON UPDATE CASCADE
ALTER TABLE Cars WITH CHECK
ADD CONSTRAINT FK_EngineID FOREIGN KEY(EngineID) REFERENCES EngineSize(EngineID)
ON UPDATE CASCADE
ALTER TABLE MFGR WITH CHECK
ADD CONSTRAINT FK_CountryID FOREIGN KEY(CountryID) REFERENCES Country(CountryID)
ON UPDATE CASCADE*/
