/*USE carsOfTheYear;
INSERT INTO Country VALUES ('1', 'Germany')
INSERT INTO Country VALUES ('2', 'Japan')
INSERT INTO Country VALUES ('3', 'UK')
INSERT INTO Country VALUES ('4', 'US')
INSERT INTO Country VALUES ('5', 'Sweden')
INSERT INTO Country VALUES ('6', 'Italy')

INSERT INTO MFGR VALUES ('1', 'BMW', '1')
INSERT INTO MFGR VALUES ('2', 'Acura', '2')
INSERT INTO MFGR VALUES ('3', 'AstonMartin', '3')
INSERT INTO MFGR VALUES ('4', 'Smart', '1')
INSERT INTO MFGR VALUES ('5', 'Chevrolet', '4')
INSERT INTO MFGR VALUES ('6', 'Chrysler', '4')
INSERT INTO MFGR VALUES ('7', 'Ferrari', '6')
INSERT INTO MFGR VALUES ('8', 'Volvo', '5')
INSERT INTO MFGR VALUES ('9', 'Audi', '1')

INSERT INTO EngineSize VALUES ('1', '4Cylinder')
INSERT INTO EngineSize VALUES ('2', '6Cylinder')
INSERT INTO EngineSize VALUES ('3', '8Cylinder')
INSERT INTO EngineSize VALUES ('4', 'Hybrid')
INSERT INTO EngineSize VALUES ('5', 'Electric')
INSERT INTO EngineSize VALUES ('6', 'Other')

INSERT INTO Performance VALUES ('1', 'Economy')
INSERT INTO Performance VALUES ('2', 'Regular')
INSERT INTO Performance VALUES ('3', 'Sports')
INSERT INTO Performance VALUES ('4', 'Utility')
INSERT INTO Performance	VALUES ('5', 'Luxury')

INSERT INTO Style VALUES ('1', 'Hatchback')
INSERT INTO Style VALUES ('2', 'Coupe')
INSERT INTO Style VALUES ('3', 'Sedan')
INSERT INTO Style VALUES ('4', 'Van')
INSERT INTO Style VALUES ('5', 'Truck')
INSERT INTO Style VALUES ('6', 'Wagon')
INSERT INTO Style VALUES ('7', 'SUV')

INSERT INTO Cars VALUES ('1', 'X7', '1', '7', '5', '2')
INSERT INTO Cars VALUES ('2', 'RDX', '2', '7', '5', '1')
INSERT INTO Cars VALUES ('3', 'DB11', '3', '2', '5', '3')
INSERT INTO Cars VALUES ('4', 'Fortwo', '4', '1', '1', '5')
INSERT INTO Cars VALUES ('5', 'Cruze', '5', '3', '2', '1')
INSERT INTO Cars VALUES ('6', 'Pacifica', '4', '4', '4', '3')
INSERT INTO Cars VALUES ('7', 'Volt', '5', '1', '2', '5')
INSERT INTO Cars VALUES ('8', 'M3', '1', '3', '3', '2')
INSERT INTO Cars VALUES ('9', 'Camero', '5', '2', '3', '3')
INSERT INTO Cars VALUES ('10', 'Colorado', '5', '5', '4', '1')
INSERT INTO Cars VALUES ('11', '749e', '1', '3', '1', '4')
INSERT INTO Cars VALUES ('12', 'e-tron', '9', '7', '4', '4')
INSERT INTO Cars VALUES ('13', '488', '7', '2', '5', '3')
INSERT INTO Cars VALUES ('14', 'S60', '8', '6', '2', '1')
INSERT INTO Cars VALUES ('15', '3 Series', '1', '2', '5', '2')
INSERT INTO Cars VALUES ('16', '300', '6', '3', '2', '3')
INSERT INTO Cars VALUES ('17', 'Superleggera', '3', '2', '3', '6')
INSERT INTO Cars VALUES ('18', 'Rapide', '3', '1', '5', '6')
INSERT INTO Cars VALUES ('19', 'A4', '9', '3', '5', '1')
INSERT INTO Cars VALUES ('20', 'NSX', '2', '2', '3', '4')*/

